import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Eye, AlertCircle } from 'lucide-react';
import { ROWS_OPTIONS_10_25_50_100 } from '../../../shared/constants/pagination';
const getStatusBadge = (value, type) => {
    const colors = { success: '#10b981', failed: '#ef4444', pending: '#f59e0b', New: '#3b82f6', Existing: '#8b5cf6', Duplicate: '#f59e0b' };
    const color = colors[value] || '#6b7280';
    return _jsx("span", { className: `${type}-badge`, style: { background: `${color}20`, color }, children: value });
};
const LeadsTable = ({ data, onViewDetails, rowsPerPage, onRowsPerPageChange, onSearchChange }) => (_jsxs(_Fragment, { children: [_jsxs("div", { className: "table-controls", children: [_jsxs("div", { className: "table-controls-left", children: [_jsx("span", { className: "show-entries", children: "Show entries" }), _jsx("select", { value: rowsPerPage, onChange: onRowsPerPageChange, children: ROWS_OPTIONS_10_25_50_100.map(n => _jsx("option", { value: n, children: n }, n)) })] }), _jsx("div", { className: "table-controls-right", children: _jsx("div", { className: "live-search", children: _jsx("input", { type: "text", placeholder: "Search...", onChange: (e) => onSearchChange(e.target.value) }) }) })] }), data.length === 0 ? (_jsxs("div", { className: "empty-state", children: [_jsx("div", { className: "empty-icon", children: _jsx(AlertCircle, { size: 48 }) }), _jsx("p", { children: "No Facebook leads found" })] })) : (_jsx("div", { className: "leads-table-wrapper", children: _jsxs("table", { className: "leads-table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "ID" }), _jsx("th", { children: "Workflow Name" }), _jsx("th", { children: "Name" }), _jsx("th", { children: "Phone Number" }), _jsx("th", { children: "Additional Data" }), _jsx("th", { children: "Status" }), _jsx("th", { children: "Lead Status" }), _jsx("th", { children: "Created At" }), _jsx("th", { children: "Failure Reason" })] }) }), _jsx("tbody", { children: data.map(lead => (_jsxs("tr", { children: [_jsx("td", { children: lead.id }), _jsx("td", { children: lead.workflowName }), _jsx("td", { children: lead.name }), _jsx("td", { children: lead.phone }), _jsx("td", { children: _jsx("button", { className: "view-data-btn", onClick: () => onViewDetails(lead), children: _jsx(Eye, { size: 14 }) }) }), _jsx("td", { children: getStatusBadge(lead.status, 'status') }), _jsx("td", { children: getStatusBadge(lead.leadStatus, 'lead') }), _jsx("td", { children: lead.createdAt }), _jsx("td", { children: lead.failureReason })] }, lead.id))) })] }) }))] }));
export default LeadsTable;
//# sourceMappingURL=LeadsTable.js.map