import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { ROWS_OPTIONS_10_25_50_100 } from '../../constants/pagination';
import { LABEL_SHOW, LABEL_ENTRIES, LABEL_FIRST, LABEL_LAST, LABEL_PREVIOUS, LABEL_NEXT, LABEL_PAGE, LABEL_OF, LABEL_SHOWING, LABEL_TO } from '../../constants/labels';
const AdminPagination = React.memo(({ currentPage, totalPages, startIndex, rowsPerPage, totalItems, onPageChange, onRowsPerPageChange, showRowsSelector, prevNextOnly, alwaysShowNav, }) => {
    const safeTotalPages = Math.max(1, Number(totalPages) || 1);
    const safeCurrentPage = Math.max(1, Number(currentPage) || 1);
    return (_jsxs("div", { className: "table-footer", children: [!prevNextOnly && showRowsSelector && (_jsx("div", { className: "entries-select", children: _jsxs("label", { children: [LABEL_SHOW, _jsx("select", { value: rowsPerPage, onChange: onRowsPerPageChange, children: ROWS_OPTIONS_10_25_50_100.map(n => _jsx("option", { value: n, children: n }, n)) }), LABEL_ENTRIES] }) })), _jsxs("div", { className: "table-info", children: [LABEL_SHOWING, " ", Math.min(startIndex + 1, totalItems), " ", LABEL_TO, " ", Math.min(startIndex + rowsPerPage, totalItems), " ", LABEL_OF, " ", totalItems, " ", LABEL_ENTRIES] }), _jsx("div", { className: "table-controls", children: (safeTotalPages > 1 || alwaysShowNav) && (_jsxs("div", { className: "pagination-controls", style: { display: 'flex', gap: '4px', alignItems: 'center' }, children: [!prevNextOnly && (_jsxs(_Fragment, { children: [_jsx("button", { className: "pagination-btn", disabled: safeCurrentPage === 1, onClick: () => onPageChange(1), children: LABEL_FIRST }), _jsx("button", { className: "pagination-btn", disabled: safeCurrentPage === 1, onClick: () => onPageChange(safeCurrentPage - 1), children: _jsx(ChevronLeft, { size: 16 }) })] })), prevNextOnly && (_jsx("button", { className: "pagination-btn", disabled: safeCurrentPage === 1, onClick: () => onPageChange(safeCurrentPage - 1), children: LABEL_PREVIOUS })), _jsxs("span", { className: "page-indicator", children: [LABEL_PAGE, " ", safeCurrentPage, " ", LABEL_OF, " ", safeTotalPages] }), !prevNextOnly && (_jsxs(_Fragment, { children: [_jsx("button", { className: "pagination-btn", disabled: safeCurrentPage === safeTotalPages, onClick: () => onPageChange(safeCurrentPage + 1), children: _jsx(ChevronRight, { size: 16 }) }), _jsx("button", { className: "pagination-btn", disabled: safeCurrentPage === safeTotalPages, onClick: () => onPageChange(safeTotalPages), children: LABEL_LAST })] })), prevNextOnly && (_jsx("button", { className: "pagination-btn", disabled: safeCurrentPage === safeTotalPages, onClick: () => onPageChange(safeCurrentPage + 1), children: LABEL_NEXT }))] })) })] }));
});
AdminPagination.displayName = 'AdminPagination';
export default AdminPagination;
//# sourceMappingURL=AdminPagination.js.map