import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Route } from 'react-router-dom';
import SettingsPage from '../features/settings/pages/SettingsPage';
import ErrorBoundary from '../shared/components/ErrorBoundary';
import LeadPurposePage from '../features/lead-settings/lead-purpose/pages/LeadPurposePage';
import LeadStatusPage from '../features/lead-settings/lead-status/pages/LeadStatusPage';
import LeadSourcePage from '../features/lead-settings/lead-source/pages/LeadSourcePage';
import LeadTypesPage from '../features/lead-settings/lead-types/pages/LeadTypesPage';
import LeadAdditionalPage from '../features/lead-settings/lead-additional/pages/LeadAdditionalPage';
import NotificationSettingsPage from '../features/notification-settings/pages/NotificationSettingsPage';
import PaymentPlansPage from '../features/payment-plans/pages/PaymentPlansPage';
import IntegrationsPage from '../features/integrations/pages/IntegrationsPage';
import LeadGenerationAPIPage from '../features/lead-generation-api/pages/LeadGenerationAPIPage';
import UserLayout from '../features/task-settings/components/UserLayout';
import CallStatusPage from '../features/task-settings/call-status/page/CallStatus';
import CallReasonPage from '../features/task-settings/call-reason/page/CallReason';
import MeetingOutcomePage from '../features/task-settings/meeting-outcome/MeetingOutcome';
import TaskCategoryPage from '../features/task-settings/task-category/page/TaskCategory';
export default (_jsxs(_Fragment, { children: [_jsx(Route, { path: "settings", element: _jsx(SettingsPage, {}) }), _jsx(Route, { path: "settings/lead-settings/purpose", element: _jsx(ErrorBoundary, { children: _jsx(LeadPurposePage, {}) }) }), _jsx(Route, { path: "settings/lead-settings/status", element: _jsx(ErrorBoundary, { children: _jsx(LeadStatusPage, {}) }) }), _jsx(Route, { path: "settings/lead-settings/source", element: _jsx(ErrorBoundary, { children: _jsx(LeadSourcePage, {}) }) }), _jsx(Route, { path: "settings/lead-settings/types", element: _jsx(ErrorBoundary, { children: _jsx(LeadTypesPage, {}) }) }), _jsx(Route, { path: "settings/lead-settings/additional", element: _jsx(ErrorBoundary, { children: _jsx(LeadAdditionalPage, {}) }) }), _jsx(Route, { path: "user/notifications-users", element: _jsx(NotificationSettingsPage, {}) }), _jsx(Route, { path: "user/payment-plans", element: _jsx(PaymentPlansPage, {}) }), _jsx(Route, { path: "user/gl-connect", element: _jsx(IntegrationsPage, {}) }), _jsx(Route, { path: "user/gl-connect/lead-api", element: _jsx(LeadGenerationAPIPage, {}) }), _jsxs(Route, { path: "user", element: _jsx(UserLayout, {}), children: [_jsx(Route, { path: "call_status", element: _jsx(CallStatusPage, {}) }), _jsx(Route, { path: "call_reasons", element: _jsx(CallReasonPage, {}) }), _jsx(Route, { path: "meeting_outcome", element: _jsx(MeetingOutcomePage, {}) }), _jsx(Route, { path: "task_categories", element: _jsx(TaskCategoryPage, {}) })] })] }));
//# sourceMappingURL=settingsRoutes.js.map