import React, { useState } from 'react';
import { Copy, RefreshCw, Check, X } from 'lucide-react';
import { NavLink } from 'react-router-dom';
import PageHeader from '../../../shared/components/layout/PageHeader';
import { apiParameters, additionalFields, tabs } from '../constants';
import type { Tab } from '../types';
import '../../../pages/LeadGenerationAPI.css';

const LeadGenerationAPIPage: React.FC = () => {
  const [apiToken, setApiToken] = useState('gl_sk_4a7f9e2c1d8b3f5a6e7c9d2a1f8b4e6c7d');
  const [copied, setCopied] = useState(false);
  const [showTokenModal, setShowTokenModal] = useState(false);
  const [activeTab, setActiveTab] = useState('introduction');

  const handleGenerateToken = () => {
    setApiToken('gl_sk_' + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15));
  };

  const handleCopyToken = () => {
    navigator.clipboard.writeText(apiToken);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const renderTabContent = () => {
    switch (activeTab) {
      case 'introduction':
        return (
          <div className="api-tab-content">
            <h3>Introduction</h3>
            <p>This API allows you to submit lead information to the GetLead CRM platform. You can create leads by providing customer information such as name, mobile number, email, and other optional fields.</p>
            <p>By connecting a webhook, users can easily receive their leads in Getlead. Alternatively, you can use our Lead Generation API to achieve the same. However, you must choose only one method (either webhook or API) and not both at the same time. Using both simultaneously may cause duplicate leads or unexpected issues. To ensure smooth lead management, please remove the connected webhook if you decide to use the API, or vice versa.</p>
            <p>That said, you can still use the Update API and Add Note API alongside webhooks without any issues.</p>

            <h4>Base URL</h4>
            <pre className="code-block">https://app.getleadcrm.com/api/gl-website-contacts</pre>

            <h4>Authentication</h4>
            <p>All API requests must include a valid API token, which can be generated by clicking the button below.</p>

            <div className="token-section">
              <button className="btn btn-primary" onClick={() => setShowTokenModal(true)}>
                Show / Generate Token
              </button>
            </div>

            <h4>Authentication Example</h4>
            <pre className="code-block">?token=your-api-token</pre>
          </div>
        );

      case 'parameters':
        return (
          <div className="api-tab-content">
            <h3>Request Parameters</h3>
            <table className="api-table">
              <thead>
                <tr>
                  <th>Parameter</th>
                  <th>Type</th>
                  <th>Required</th>
                  <th>Description</th>
                </tr>
              </thead>
              <tbody>
                {apiParameters.map((param, index) => (
                  <tr key={index}>
                    <td><code>{param.parameter}</code></td>
                    <td>{param.type}</td>
                    <td><span className={`required-badge ${param.required.toLowerCase()}`}>{param.required}</span></td>
                    <td>{param.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            <h4>Additional Fields</h4>
            <p>In addition to the required parameters, the API supports the following optional fields:</p>
            <table className="api-table">
              <tbody>
                {additionalFields.map((field, index) => (
                  <tr key={index}>
                    <td><code>{field.parameter}</code></td>
                    <td>{field.type}</td>
                    <td><span className={`required-badge ${field.required.toLowerCase()}`}>{field.required}</span></td>
                    <td>{field.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );

      case 'example':
        return (
          <div className="api-tab-content">
            <h3>Sample API Request</h3>
            <p>You can use the following sample request to create a lead:</p>

            <pre className="code-block large">
              GET https://app.getleadcrm.com/api/gl-website-contacts?token=gl_8fba4bd0_*****&name=John+Doe&countrycode=91&mobileno=1234567890&email=johndoe@email.com&source=Demo+request&more_phone_numbers=9876543210,9876543211
            </pre>
          </div>
        );

      case 'response':
        return (
          <div className="api-tab-content">
            <h3>Response</h3>
            <p>The API will return a JSON response indicating the success or failure of the request.</p>

            <h4>Sample Success Response</h4>
            <pre className="code-block">{`{
  "message": "Lead created successfully",
  "status": "success"
}`}</pre>

            <h4>Sample Error Response</h4>
            <pre className="code-block">{`{
  "message": "Lead already exists",
  "status": "fail"
}`}</pre>

            <pre className="code-block">{`{
  "message": "The mobileno must be valid and between 8 and 14 digits.",
  "status": "fail"
}`}</pre>

            <pre className="code-block">{`{
  "message": "Please check the parameters",
  "status": "fail"
}`}</pre>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="lead-api-page">
      <PageHeader
        title="Lead Generation API"
        description="Configure developer API for lead submission"
        breadcrumb={[
          { label: 'Integrations', link: '/user/gl-connect' },
          { label: 'Lead Generation API' }
        ]}
      />

      <div className="api-page-content">
        <div className="api-tabs">
          {tabs.map((tab: Tab) => (
            <button
              key={tab.id}
              className={`api-tab ${activeTab === tab.id ? 'active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div className="api-content-section">
          {renderTabContent()}
        </div>
      </div>

      {showTokenModal && (
        <div className="modal-overlay" onClick={() => setShowTokenModal(false)}>
          <div className="modal-content token-modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>API Token</h3>
              <button className="modal-close" onClick={() => setShowTokenModal(false)}>
                <X size={20} />
              </button>
            </div>
            <div className="modal-body">
              <div className="token-display">
                <label>Your API Token</label>
                <div className="token-input-group">
                  <input
                    type="text"
                    value={apiToken}
                    readOnly
                    className="form-control"
                  />
                  <button
                    className="copy-btn"
                    onClick={handleCopyToken}
                  >
                    {copied ? <Check size={18} /> : <Copy size={18} />}
                  </button>
                </div>
              </div>

              <button
                className="btn btn-outline regenerate-btn"
                onClick={handleGenerateToken}
              >
                <RefreshCw size={16} /> Regenerate Token
              </button>

              <p className="token-note">
                Last generated: {new Date().toLocaleDateString()}
              </p>

              <div className="token-warning">
                <strong>Warning:</strong> Keep your API token secure. Do not share it publicly.
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default LeadGenerationAPIPage;
