import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Copy, RefreshCw, Check, X } from 'lucide-react';
import { useLeadGenerationAPIData } from '../hooks/useLeadGenerationAPIData';
import PageHeader from '../../../shared/components/layout/PageHeader';
import { apiParameters, additionalFields, tabs } from '../constants';
import './LeadGenerationAPIPage.css';
const LeadGenerationAPIPage = () => {
    const d = useLeadGenerationAPIData();
    const renderTabContent = () => {
        switch (d.activeTab) {
            case 'introduction':
                return (_jsxs("div", { className: "api-tab-content", children: [_jsx("h3", { children: "Introduction" }), _jsx("p", { children: "This API allows you to submit lead information to the GetLead CRM platform. You can create leads by providing customer information such as name, mobile number, email, and other optional fields." }), _jsx("p", { children: "By connecting a webhook, users can easily receive their leads in Getlead. Alternatively, you can use our Lead Generation API to achieve the same. However, you must choose only one method (either webhook or API) and not both at the same time. Using both simultaneously may cause duplicate leads or unexpected issues. To ensure smooth lead management, please remove the connected webhook if you decide to use the API, or vice versa." }), _jsx("p", { children: "That said, you can still use the Update API and Add Note API alongside webhooks without any issues." }), _jsx("h4", { children: "Base URL" }), _jsx("pre", { className: "code-block", children: "https://app.getleadcrm.com/api/gl-website-contacts" }), _jsx("h4", { children: "Authentication" }), _jsx("p", { children: "All API requests must include a valid API token, which can be generated by clicking the button below." }), _jsx("div", { className: "token-section", children: _jsx("button", { className: "btn btn-primary", onClick: () => d.setShowTokenModal(true), children: "Show / Generate Token" }) }), _jsx("h4", { children: "Authentication Example" }), _jsx("pre", { className: "code-block", children: "?token=your-api-token" })] }));
            case 'parameters':
                return (_jsxs("div", { className: "api-tab-content", children: [_jsx("h3", { children: "Request Parameters" }), _jsxs("table", { className: "api-table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Parameter" }), _jsx("th", { children: "Type" }), _jsx("th", { children: "Required" }), _jsx("th", { children: "Description" })] }) }), _jsx("tbody", { children: apiParameters.map((param, index) => (_jsxs("tr", { children: [_jsx("td", { children: _jsx("code", { children: param.parameter }) }), _jsx("td", { children: param.type }), _jsx("td", { children: _jsx("span", { className: `required-badge ${param.required.toLowerCase()}`, children: param.required }) }), _jsx("td", { children: param.description })] }, index))) })] }), _jsx("h4", { children: "Additional Fields" }), _jsx("p", { children: "In addition to the required parameters, the API supports the following optional fields:" }), _jsx("table", { className: "api-table", children: _jsx("tbody", { children: additionalFields.map((field, index) => (_jsxs("tr", { children: [_jsx("td", { children: _jsx("code", { children: field.parameter }) }), _jsx("td", { children: field.type }), _jsx("td", { children: _jsx("span", { className: `required-badge ${field.required.toLowerCase()}`, children: field.required }) }), _jsx("td", { children: field.description })] }, index))) }) })] }));
            case 'example':
                return (_jsxs("div", { className: "api-tab-content", children: [_jsx("h3", { children: "Sample API Request" }), _jsx("p", { children: "You can use the following sample request to create a lead:" }), _jsx("pre", { className: "code-block large", children: "GET https://app.getleadcrm.com/api/gl-website-contacts?token=gl_8fba4bd0_*****&name=John+Doe&countrycode=91&mobileno=1234567890&email=johndoe@email.com&source=Demo+request&more_phone_numbers=9876543210,9876543211" })] }));
            case 'response':
                return (_jsxs("div", { className: "api-tab-content", children: [_jsx("h3", { children: "Response" }), _jsx("p", { children: "The API will return a JSON response indicating the success or failure of the request." }), _jsx("h4", { children: "Sample Success Response" }), _jsx("pre", { className: "code-block", children: `{
  "message": "Lead created successfully",
  "status": "success"
}` }), _jsx("h4", { children: "Sample Error Response" }), _jsx("pre", { className: "code-block", children: `{
  "message": "Lead already exists",
  "status": "fail"
}` }), _jsx("pre", { className: "code-block", children: `{
  "message": "The mobileno must be valid and between 8 and 14 digits.",
  "status": "fail"
}` }), _jsx("pre", { className: "code-block", children: `{
  "message": "Please check the parameters",
  "status": "fail"
}` })] }));
            default:
                return null;
        }
    };
    return (_jsxs("div", { className: "lead-api-page", children: [_jsx(PageHeader, { title: "Lead Generation API", description: "Configure developer API for lead submission", breadcrumb: [
                    { label: 'Integrations', link: '/user/gl-connect' },
                    { label: 'Lead Generation API' }
                ] }), _jsxs("div", { className: "api-page-content", children: [_jsx("div", { className: "api-tabs", children: tabs.map((tab) => (_jsx("button", { className: `api-tab ${d.activeTab === tab.id ? 'active' : ''}`, onClick: () => d.setActiveTab(tab.id), children: tab.label }, tab.id))) }), _jsx("div", { className: "api-content-section", children: renderTabContent() })] }), d.showTokenModal && (_jsx("div", { className: "modal-overlay", onClick: () => d.setShowTokenModal(false), children: _jsxs("div", { className: "modal-content token-modal", onClick: e => e.stopPropagation(), children: [_jsxs("div", { className: "modal-header", children: [_jsx("h3", { children: "API Token" }), _jsx("button", { className: "modal-close", onClick: () => d.setShowTokenModal(false), children: _jsx(X, { size: 20 }) })] }), _jsxs("div", { className: "modal-body", children: [_jsxs("div", { className: "token-display", children: [_jsx("label", { children: "Your API Token" }), _jsxs("div", { className: "token-input-group", children: [_jsx("input", { type: "text", value: d.apiToken, readOnly: true, className: "form-control" }), _jsx("button", { className: "copy-btn", onClick: d.handleCopyToken, children: d.copied ? _jsx(Check, { size: 18 }) : _jsx(Copy, { size: 18 }) })] })] }), _jsxs("button", { className: "btn btn-outline regenerate-btn", onClick: d.handleGenerateToken, children: [_jsx(RefreshCw, { size: 16 }), " Regenerate Token"] }), _jsxs("p", { className: "token-note", children: ["Last generated: ", new Date().toLocaleDateString()] }), _jsxs("div", { className: "token-warning", children: [_jsx("strong", { children: "Warning:" }), " Keep your API token secure. Do not share it publicly."] })] })] }) }))] }));
};
export default LeadGenerationAPIPage;
//# sourceMappingURL=LeadGenerationAPIPage.js.map