export const integrationsData = [
    {
        id: 'lead-api',
        name: 'Lead Generation API',
        subtitle: 'Configure developer API',
        category: 'Developer Tools',
        description: 'Use our API to programmatically create and manage leads in your CRM. Supports REST API with JSON responses.',
        icon: '⚡',
        configFields: ['apiKey', 'endpoint', 'webhook'],
    },
    {
        id: 'facebook',
        name: 'Facebook',
        subtitle: 'Social media platform',
        category: 'Social Media',
        description: 'Connect Facebook to capture leads directly from your Facebook ads and pages.',
        icon: '📘',
        configFields: ['appId', 'appSecret', 'webhookUrl'],
        hasViewLeads: true,
    },
    {
        id: 'telinfy',
        name: 'Telinfy',
        subtitle: 'Messaging platform',
        category: 'Messaging',
        description: 'Telinfy messaging integration for automated WhatsApp conversations.',
        icon: '💬',
        configFields: ['apiKey', 'instanceId', 'webhookUrl'],
    },
    {
        id: 'chatspaz',
        name: 'Chatspaz',
        subtitle: 'Messaging platform',
        category: 'Messaging',
        description: 'Chatspaz integration for customer engagement and support.',
        icon: '💭',
        configFields: ['apiKey', 'webhookUrl'],
    },
    {
        id: 'interakt',
        name: 'Interakt',
        subtitle: 'Messaging platform',
        category: 'Messaging',
        description: 'Interakt WhatsApp business solution for CRM integration.',
        icon: '📱',
        configFields: ['apiKey', 'instanceId', 'webhookUrl'],
    },
    {
        id: 'waba',
        name: 'WABA',
        subtitle: 'Messaging platform',
        category: 'Messaging',
        description: 'WhatsApp Business API integration for bulk messaging and automation.',
        icon: '✅',
        configFields: ['phoneNumberId', 'token', 'webhookUrl'],
    },
];
//# sourceMappingURL=index.js.map