import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Eye, EyeOff, Lock, KeyRound, CheckCircle, XCircle, Loader2, Check, X } from 'lucide-react';
import { Formik, Form, Field } from 'formik';
import PageHeader from '../../../../shared/components/layout/PageHeader';
import SettingsTabs from '../../../../shared/components/SettingsTabs';
import { usePasswordData } from '../hooks/usePasswordData';
import { changePasswordValidationSchema } from '../validations/password.validation';
import { INITIAL_PASSWORD_FORM, PASSWORD_PAGE_CONTENT_STYLE } from '../constants';
import './PasswordPage.css';
const PasswordPage = () => {
    const { isLoading, showCurrentPassword, showNewPassword, showConfirmPassword, toastMessage, toastType, showToast, setShowCurrentPassword, setShowNewPassword, setShowConfirmPassword, setShowToast, getPasswordStrength, handleSubmit, } = usePasswordData();
    return (_jsxs("div", { className: "account-page", children: [_jsx("div", { className: "account-layout", children: _jsxs("div", { className: "account-content", style: PASSWORD_PAGE_CONTENT_STYLE, children: [_jsx(PageHeader, { title: "Change Password", description: "Update your account password" }), _jsx(SettingsTabs, {}), _jsx("div", { className: "row", children: _jsx("div", { className: "col-lg-8 col-md-8", children: _jsxs("div", { className: "password-page-card", children: [_jsx("div", { className: "card-header", children: _jsx("h5", { children: "Change Password" }) }), _jsx("div", { className: "card-body", children: _jsx(Formik, { enableReinitialize: true, initialValues: INITIAL_PASSWORD_FORM, validationSchema: changePasswordValidationSchema, onSubmit: handleSubmit, children: ({ values, errors, touched, submitCount }) => {
                                                    const passwordStrength = getPasswordStrength(values.newPassword);
                                                    const showError = (field) => touched[field] || submitCount > 0;
                                                    return (_jsxs(Form, { children: [_jsxs("div", { className: "form-group", children: [_jsxs("label", { children: ["Current Password ", _jsx("span", { className: "text-danger", children: "*" })] }), _jsxs("div", { className: "password-input-wrapper", children: [_jsx(Lock, { size: 18, className: "input-icon" }), _jsx(Field, { type: showCurrentPassword ? 'text' : 'password', name: "currentPassword", className: "form-control with-icon", placeholder: "Enter current password" }), _jsx("span", { className: "field-icon", onClick: () => setShowCurrentPassword(!showCurrentPassword), children: showCurrentPassword ? _jsx(EyeOff, { size: 18 }) : _jsx(Eye, { size: 18 }) })] }), showError('currentPassword') && errors.currentPassword && (_jsx("small", { className: "field-error-text", children: errors.currentPassword }))] }), _jsxs("div", { className: "form-group", children: [_jsxs("label", { children: ["New Password ", _jsx("span", { className: "text-danger", children: "*" })] }), _jsxs("div", { className: "password-input-wrapper", children: [_jsx(KeyRound, { size: 18, className: "input-icon" }), _jsx(Field, { type: showNewPassword ? 'text' : 'password', name: "newPassword", className: "form-control with-icon", placeholder: "Enter new password" }), _jsx("span", { className: "field-icon", onClick: () => setShowNewPassword(!showNewPassword), children: showNewPassword ? _jsx(EyeOff, { size: 18 }) : _jsx(Eye, { size: 18 }) })] }), values.newPassword && (_jsxs("div", { className: "password-strength", children: [_jsx("div", { className: "strength-bar", children: _jsx("div", { className: "strength-fill", style: {
                                                                                        width: `${passwordStrength.strength * 25}%`,
                                                                                        background: passwordStrength.color
                                                                                    } }) }), _jsx("span", { className: "strength-text", style: { color: passwordStrength.color }, children: passwordStrength.text })] })), showError('newPassword') && errors.newPassword && (_jsx("small", { className: "field-error-text", children: errors.newPassword }))] }), _jsxs("div", { className: "form-group", children: [_jsxs("label", { children: ["Confirm Password ", _jsx("span", { className: "text-danger", children: "*" })] }), _jsxs("div", { className: "password-input-wrapper", children: [_jsx(KeyRound, { size: 18, className: "input-icon" }), _jsx(Field, { type: showConfirmPassword ? 'text' : 'password', name: "confirmPassword", className: "form-control with-icon", placeholder: "Confirm new password" }), _jsx("span", { className: "field-icon", onClick: () => setShowConfirmPassword(!showConfirmPassword), children: showConfirmPassword ? _jsx(EyeOff, { size: 18 }) : _jsx(Eye, { size: 18 }) })] }), values.confirmPassword && values.newPassword === values.confirmPassword && (_jsxs("span", { className: "text-success", children: [_jsx(CheckCircle, { size: 14 }), " Passwords match"] })), values.confirmPassword && values.newPassword !== values.confirmPassword && (_jsxs("span", { className: "text-danger", children: [_jsx(XCircle, { size: 14 }), " Passwords do not match"] })), showError('confirmPassword') && errors.confirmPassword && (_jsx("small", { className: "field-error-text", children: errors.confirmPassword }))] }), _jsx("div", { className: "form-actions", children: _jsxs("button", { type: "submit", className: "btn btn-primary", disabled: isLoading, children: [isLoading ? _jsx(Loader2, { size: 16, className: "spin" }) : _jsx(Lock, { size: 16 }), ' ', " Change Password"] }) })] }));
                                                } }) })] }) }) })] }) }), showToast && (_jsxs("div", { className: `toast-notification toast-${toastType}`, onClick: () => setShowToast(false), children: [toastType === 'success' ? _jsx(Check, { size: 18 }) : _jsx(X, { size: 18 }), _jsx("span", { children: toastMessage })] }))] }));
};
export default PasswordPage;
//# sourceMappingURL=PasswordPage.js.map