import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Plus, GripVertical, ArrowRight, Check, Trash2, Save } from 'lucide-react';
import PageHeader from '../../../shared/components/layout/PageHeader';
import PageContainer from '../../../shared/components/layout/PageContainer';
import { useSetupData } from '../hooks/useSetupData';
import './SetupPage.css';
const SetupPage = () => {
    const { stages, savedStages, newStageName, setNewStageName, editingStage, setEditingStage, handleAddStage, handleDeleteStage, handleUpdateStage, handleSave, handleReset, moveStage, } = useSetupData();
    return (_jsxs(PageContainer, { children: [_jsx(PageHeader, { title: "Setup", description: "Configure your CRM pipeline and tracking stages" }), _jsx("div", { className: "pipeline-visual", children: savedStages.map((stage, index) => (_jsxs(React.Fragment, { children: [_jsxs("div", { className: "pipeline-stage-box", children: [_jsx("div", { className: "stage-box-color", style: { background: stage.color } }), _jsx("span", { children: stage.name })] }), index < savedStages.length - 1 && (_jsx("div", { className: "pipeline-arrow", children: _jsx(ArrowRight, { size: 16 }) }))] }, stage.id))) }), _jsx("div", { className: "setup-content", children: _jsxs("div", { className: "setup-card", children: [_jsxs("div", { className: "card-header", children: [_jsx("h3", { children: "Sales Pipeline Stages" }), _jsx("p", { children: "Define the stages your leads go through from creation to conversion" })] }), _jsx("div", { className: "stages-flow", children: stages.map((stage, index) => (_jsxs(React.Fragment, { children: [_jsxs("div", { className: "stage-item", children: [_jsx("div", { className: "stage-drag", children: _jsx(GripVertical, { size: 16 }) }), _jsx("div", { className: "stage-color", style: { background: stage.color } }), editingStage === stage.id ? (_jsxs("div", { className: "stage-edit-form", children: [_jsx("input", { type: "text", value: stage.name, onChange: (e) => handleUpdateStage(stage.id, e.target.value, stage.color), autoFocus: true }), _jsx("input", { type: "color", value: stage.color, onChange: (e) => handleUpdateStage(stage.id, stage.name, e.target.value) }), _jsx("button", { onClick: () => setEditingStage(null), children: _jsx(Check, { size: 16 }) })] })) : (_jsx("span", { className: "stage-name", onClick: () => setEditingStage(stage.id), children: stage.name })), _jsxs("div", { className: "stage-actions", children: [_jsx("button", { onClick: () => moveStage(index, -1), disabled: index === 0, children: "\u2191" }), _jsx("button", { onClick: () => moveStage(index, 1), disabled: index === stages.length - 1, children: "\u2193" }), _jsx("button", { onClick: () => handleDeleteStage(stage.id), className: "delete-btn", children: _jsx(Trash2, { size: 14 }) })] })] }), index < stages.length - 1 && (_jsx("div", { className: "stage-connector", children: _jsx(ArrowRight, { size: 16 }) }))] }, stage.id))) }), _jsxs("div", { className: "add-stage-form", children: [_jsx("input", { type: "text", placeholder: "New stage name", value: newStageName, onChange: (e) => setNewStageName(e.target.value) }), _jsxs("button", { onClick: handleAddStage, children: [_jsx(Plus, { size: 16 }), " Add Stage"] })] }), _jsxs("div", { className: "form-actions", children: [_jsx("button", { className: "btn btn-secondary", onClick: handleReset, children: "Reset Changes" }), _jsxs("button", { className: "btn btn-primary", onClick: handleSave, children: [_jsx(Save, { size: 16 }), " Save Changes"] })] })] }) })] }));
};
export default SetupPage;
//# sourceMappingURL=SetupPage.js.map