export const DEFAULT_COUNTRY_CODE = '+91';
export const COUNTRY_CODES = [
    { country: 'India', code: '+91' },
    { country: 'United States', code: '+1' },
    { country: 'Canada', code: '+1' },
    { country: 'United Kingdom', code: '+44' },
    { country: 'Australia', code: '+61' },
    { country: 'United Arab Emirates', code: '+971' },
    { country: 'Saudi Arabia', code: '+966' },
    { country: 'Qatar', code: '+974' },
    { country: 'Kuwait', code: '+965' },
    { country: 'Bahrain', code: '+973' },
    { country: 'Oman', code: '+968' },
    { country: 'Singapore', code: '+65' },
    { country: 'Malaysia', code: '+60' },
    { country: 'Indonesia', code: '+62' },
    { country: 'Thailand', code: '+66' },
    { country: 'Philippines', code: '+63' },
    { country: 'Vietnam', code: '+84' },
    { country: 'China', code: '+86' },
    { country: 'Hong Kong', code: '+852' },
    { country: 'Japan', code: '+81' },
    { country: 'South Korea', code: '+82' },
    { country: 'Pakistan', code: '+92' },
    { country: 'Bangladesh', code: '+880' },
    { country: 'Sri Lanka', code: '+94' },
    { country: 'Nepal', code: '+977' },
    { country: 'Germany', code: '+49' },
    { country: 'France', code: '+33' },
    { country: 'Italy', code: '+39' },
    { country: 'Spain', code: '+34' },
    { country: 'Netherlands', code: '+31' },
    { country: 'Switzerland', code: '+41' },
    { country: 'Sweden', code: '+46' },
    { country: 'Norway', code: '+47' },
    { country: 'Denmark', code: '+45' },
    { country: 'Ireland', code: '+353' },
    { country: 'Portugal', code: '+351' },
    { country: 'Belgium', code: '+32' },
    { country: 'Russia', code: '+7' },
    { country: 'South Africa', code: '+27' },
    { country: 'Nigeria', code: '+234' },
    { country: 'Kenya', code: '+254' },
    { country: 'Egypt', code: '+20' },
    { country: 'Brazil', code: '+55' },
    { country: 'Mexico', code: '+52' },
    { country: 'Argentina', code: '+54' },
    { country: 'New Zealand', code: '+64' },
];
//# sourceMappingURL=countryCodes.js.map