import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search, Plus } from 'lucide-react';
import AdminTable from '../../../../shared/components/crud/AdminTable';
import { ROWS_OPTIONS_10_25_50_100 } from '../../../../shared/constants/pagination';
import { LABEL_SHOW, LABEL_ENTRIES } from '../../../../shared/constants/labels';
import { ACTION_SEARCH } from '../../../../shared/constants/actionLabels';
import { ADDITIONAL_FIELD_COLUMNS } from '../types/deal-additional-field-table.types';
import DealAdditionalFieldActionMenu from './DealAdditionalFieldActionMenu';
const DealAdditionalFieldTable = ({ data, searchQuery, onSearchChange, onAdd, addLabel, rowsPerPage, onRowsPerPageChange, startIndex, dropdownOpen, dropdownDirection, setDropdownOpen, setDropdownDirection, handleEditClick, handleDeleteClick, page, totalPages, total, onPageChange, }) => (_jsxs("div", { className: "table-container", children: [_jsxs("div", { className: "table-header-controls", children: [_jsx("div", { className: "entries-select", children: _jsxs("label", { children: [LABEL_SHOW, _jsx("select", { value: rowsPerPage, onChange: onRowsPerPageChange, children: ROWS_OPTIONS_10_25_50_100.map(n => _jsx("option", { value: n, children: n }, n)) }), LABEL_ENTRIES] }) }), _jsxs("div", { style: { display: 'flex', gap: '8px', alignItems: 'center' }, children: [_jsxs("div", { className: "search-input", children: [_jsx(Search, { size: 16 }), _jsx("input", { type: "search", placeholder: ACTION_SEARCH, value: searchQuery, onChange: (e) => onSearchChange(e.target.value) })] }), _jsxs("button", { className: "btn btn-primary", onClick: onAdd, children: [_jsx(Plus, { size: 16 }), " ", addLabel] })] })] }), _jsx(AdminTable, { data: data, columns: ADDITIONAL_FIELD_COLUMNS, startIndex: startIndex, dropdownOpen: null, onToggleDropdown: () => { }, onEdit: (item) => handleEditClick(item), onDelete: (item) => handleDeleteClick(item), renderActions: (item) => (_jsx(DealAdditionalFieldActionMenu, { item: item, dropdownOpen: dropdownOpen, onToggle: setDropdownOpen, dropdownDirection: dropdownDirection, onDirectionChange: setDropdownDirection, onEdit: handleEditClick, onDelete: handleDeleteClick })) })] }));
export default DealAdditionalFieldTable;
//# sourceMappingURL=DealAdditionalFieldTable.js.map