import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Check, X } from 'lucide-react';
import { useDesignationPage } from '../hooks';
import AddDesignationDrawer from '../components/AddDesignationDrawer';
import AdminDeleteModal from '../../../../shared/components/crud/AdminDeleteModal';
import PageHeader from '../../../../shared/components/layout/PageHeader';
import SettingsTabs from '../../../../shared/components/SettingsTabs';
import { SettingsTableLayout } from '../../../../shared/components/settings';
import { DESIGNATION_TABLE_COLUMNS } from '../constants/designationTableColumns';
const DesignationPage = () => {
    const { designation, searchQuery, handleSearchChange, rowsPerPage, handleRowsPerPageChange, pageNumber, setPageNumber, totalCount, startIndex, totalPages, showDrawer, dropdownOpen, onToggleDropdown, editingItem, deletingItem, filteredData, drawerInitialValues, handleAddClick, handleCloseDrawer, handleEditClick, handleDeleteClick, handleConfirmDelete, handleCloseDeleteModal, handleSubmit, handleEditSubmit, } = useDesignationPage();
    return (_jsxs("div", { className: "account-page", children: [_jsx(PageHeader, { title: "Account Settings", description: "Manage your login credentials, settings, and preferences" }), _jsx(SettingsTabs, {}), _jsxs("div", { className: "account-content", style: { width: '100%', maxWidth: '100%' }, children: [_jsx(SettingsTableLayout, { searchQuery: searchQuery, onSearchChange: handleSearchChange, onAdd: handleAddClick, addLabel: "Add Designation", data: filteredData, columns: DESIGNATION_TABLE_COLUMNS, startIndex: startIndex, dropdownOpen: dropdownOpen, onToggleDropdown: onToggleDropdown, onEdit: handleEditClick, onDelete: handleDeleteClick, currentPage: pageNumber, totalPages: totalPages, rowsPerPage: rowsPerPage, totalItems: totalCount, onPageChange: setPageNumber, onRowsPerPageChange: handleRowsPerPageChange }), _jsx(AddDesignationDrawer, { isOpen: showDrawer, onClose: handleCloseDrawer, validationSchema: editingItem ? designation.editValidationSchema : designation.validationSchema, initialValues: drawerInitialValues, onSubmit: editingItem ? handleEditSubmit : handleSubmit, isLoading: designation.isLoading, error: designation.error, isEditing: !!editingItem }), !!deletingItem && !designation.dependencyError && (_jsx(AdminDeleteModal, { isOpen: !!deletingItem, itemName: deletingItem?.designationName || deletingItem?.name || '', onConfirm: handleConfirmDelete, onClose: handleCloseDeleteModal })), designation.dependencyError && (_jsx("div", { className: "modal-overlay", onClick: designation.clearDependencyError, children: _jsxs("div", { className: "modal-content", onClick: (e) => e.stopPropagation(), style: { maxWidth: '450px' }, children: [_jsxs("div", { className: "modal-header", children: [_jsx("h5", { children: "Cannot Delete Designation" }), _jsx("button", { className: "modal-close", onClick: designation.clearDependencyError, children: _jsx(X, { size: 20 }) })] }), _jsx("div", { className: "modal-body", children: _jsx("p", { className: "delete-warning", children: "This designation is currently assigned to one or more staff members. Please reassign or remove those staff members before deleting this designation." }) }), _jsx("div", { className: "modal-footer", children: _jsx("button", { className: "btn btn-primary", onClick: designation.clearDependencyError, children: "OK" }) })] }) })), designation.showToast && (_jsxs("div", { className: `toast-notification toast-${designation.toastType}`, onClick: () => designation.setShowToast(false), children: [designation.toastType === 'success' ? _jsx(Check, { size: 18 }) : _jsx(X, { size: 18 }), _jsx("span", { children: designation.toastMessage })] }))] })] }));
};
export default DesignationPage;
//# sourceMappingURL=DesignationPage.js.map