import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from 'react';
import { ChevronLeft, ChevronRight, Search, User } from 'lucide-react';
import { AGENTS, MONTH_NAMES } from '../constants';
const CalendarControls = ({ viewMode, onViewModeChange, currentDate, onPrevMonth, onNextMonth, onTodayClick, selectedAgent, onAgentChange, selectedAgentName, showAgentDropdown, onSetShowAgentDropdown, searchQuery, onSearchChange, }) => {
    const filteredAgents = useMemo(() => AGENTS.filter(a => a.name.toLowerCase().includes(searchQuery.toLowerCase())), [searchQuery]);
    return (_jsxs("div", { className: "calendar-controls", children: [_jsx("div", { className: "calendar-controls-left", children: _jsxs("div", { className: "agent-select-wrapper", children: [_jsxs("div", { className: "agent-select-trigger", onClick: () => onSetShowAgentDropdown(!showAgentDropdown), children: [_jsx("span", { children: selectedAgentName }), _jsx(ChevronRight, { size: 16, className: `dropdown-arrow ${showAgentDropdown ? 'open' : ''}` })] }), showAgentDropdown && (_jsxs("div", { className: "agent-dropdown", children: [_jsxs("div", { className: "agent-search-box", children: [_jsx(Search, { size: 14 }), _jsx("input", { type: "text", placeholder: "Search agents...", value: searchQuery, onChange: (e) => onSearchChange(e.target.value) })] }), _jsx("div", { className: "agent-list", children: filteredAgents.map(agent => (_jsxs("div", { className: `agent-option ${selectedAgent === agent.id ? 'selected' : ''}`, onClick: () => { onAgentChange(agent.id); onSetShowAgentDropdown(false); }, children: [_jsx(User, { size: 14 }), _jsx("span", { children: agent.name })] }, agent.id))) })] }))] }) }), _jsxs("div", { className: "calendar-controls-right", children: [_jsxs("div", { className: "view-switch-buttons", children: [_jsx("button", { className: `view-btn ${viewMode === 'day' ? 'active' : ''}`, onClick: () => onViewModeChange('day'), children: "Day" }), _jsx("button", { className: `view-btn ${viewMode === 'week' ? 'active' : ''}`, onClick: () => onViewModeChange('week'), children: "Week" }), _jsx("button", { className: `view-btn ${viewMode === 'month' ? 'active' : ''}`, onClick: () => onViewModeChange('month'), children: "Month" })] }), _jsxs("div", { className: "month-navigation", children: [_jsx("button", { className: "nav-btn", onClick: onPrevMonth, children: _jsx(ChevronLeft, { size: 18 }) }), _jsx("span", { className: "current-month", children: viewMode === 'day'
                                    ? `${MONTH_NAMES[currentDate.getMonth()]} ${currentDate.getDate()}, ${currentDate.getFullYear()}`
                                    : viewMode === 'week'
                                        ? `Week of ${MONTH_NAMES[currentDate.getMonth()]} ${currentDate.getDate() - currentDate.getDay() + 1}, ${currentDate.getFullYear()}`
                                        : `${MONTH_NAMES[currentDate.getMonth()]} ${currentDate.getFullYear()}` }), _jsx("button", { className: "nav-btn", onClick: onNextMonth, children: _jsx(ChevronRight, { size: 18 }) })] })] })] }));
};
export default CalendarControls;
//# sourceMappingURL=CalendarControls.js.map