export const permissionsData: Record<string, { name: string; actions: string[] }[]> = {
  CRM: [
    { name: 'Home', actions: ['View'] },
    { name: 'Dashboard', actions: ['View', 'Dashboard'] },
    { name: 'Change Password', actions: ['View', 'Store'] },
    { name: 'Profile', actions: ['View', 'Show', 'Update'] },
    { name: 'Settings', actions: ['View'] },
    { name: 'User Data', actions: ['Update'] },
    { name: 'MailConfiguration', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete', 'Data', 'Activate', 'Deactivate', 'Default'] },
    { name: 'Designations', actions: ['List', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Agent', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete', 'View Dashboard', 'Location History', 'Location map', 'View Data'] },
    { name: 'Leads', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete', 'Data', 'Import Page', 'TimeLine', 'Edit', 'TimeLine Edit', 'TimeLine Update', 'TimeLine Add Note', 'TimeLine Delete', 'Multiple Delete', 'Update lead profile', 'Timeline status change', 'Import Step1', 'Import step2', 'Import step3'] },
    { name: 'Activity', actions: ['View'] },
    { name: 'Facebook Leads', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Calendar', actions: ['List', 'Create', 'View', 'Edit'] },
    { name: 'Group', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Auto Assign', actions: ['List', 'Create', 'Store'] },
    { name: 'Assign To Agent', actions: ['Assign', 'Assign to Multiple'] },
    { name: 'Enquiry Source', actions: ['List', 'Store', 'View', 'Update', 'Delete', 'Data', 'Activate', 'Deactivate'] },
    { name: 'Enquiry Purpose', actions: ['List', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Enquiry Status', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Export', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Whatsapp Template', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete', 'Data', 'Choose template'] },
    { name: 'SMS Templates', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Email Template', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Lead Types', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Fields', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Followup', actions: ['List', 'Add', 'Update', 'Data'] },
    { name: 'Tasks', actions: ['List', 'Data', 'Import', 'Import Data', 'Delete Multiple', 'Delete', 'Create from Timeline', 'Update', 'Show'] },
    { name: 'Task Category', actions: ['List', 'Data', 'Create', 'Edit', 'Update', 'Store', 'Delete'] },
    { name: 'Calls', actions: ['List', 'Complete Call', 'Complete call push', 'Complete multiple task'] },
    { name: 'Timeline', actions: ['Add Log'] },
    { name: 'Deals', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete', 'Get deal data', 'Update timeline data', 'Deal activity', 'Assign deal agent', 'Deal timeline note', 'Get deal note', 'Edit', 'Get Lead Company'] },
    { name: 'Reports', actions: ['Lead Reports', 'Deal Reports', 'Task Reports', 'Checking report', 'Attendance', 'Checking data', 'Attandance list', 'Attandace details'] },
    { name: 'Lead Reports', actions: ['Daily activity', 'Activity Data', 'Status Vise', 'Status vise data', 'Status Change', 'Status change data', 'Source Change', 'Source change data', 'Staff checkin', 'Checkin data', 'Import History', 'Api History', 'History data'] },
    { name: 'Deal Reports', actions: ['Deal Summary', 'Summary data', 'Deal Stage', 'Deal stage data', 'Lead conversion', 'Data'] },
    { name: 'Task Reports', actions: ['Task Vise', 'Data fetch', 'Lead vise', 'Data get'] },
    { name: 'Timeline Activities', actions: ['View Tasks', 'View Deals', 'View Activities', 'View Log Notes', 'View Orders', 'Update Tasks'] },
  ],
  SMS: [
    { name: 'Sms Dashboard', actions: ['View'] },
    { name: 'Compose SMS', actions: ['Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Dynamic Messaging', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Sender Id', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete', 'Data'] },
    { name: 'API Template', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'SMS History', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
  ],
  IVR: [
    { name: 'Ivr Dashboard', actions: ['View'] },
    { name: 'Ivr Flow', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete', 'Data'] },
    { name: 'Ivr Call Logs', actions: ['List', 'View', 'Data'] },
  ],
  Sales: [
    { name: 'Sales Dashboard', actions: ['View'] },
    { name: 'Product', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete', 'Data'] },
    { name: 'Product Category', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Tax', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Coupon', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
    { name: 'Pos', actions: ['List', 'Create', 'Store', 'View', 'Update', 'Delete'] },
  ],
};
