export const INITIAL_FILTERS = {
  type: '',
  dateRange: { start: '', end: '' },
  filterByDate: '',
  enquirySource: '',
  enquiryPurpose: '',
  leadStatus: '',
  followupAdded: '',
  createdBy: '',
  assignedTo: '',
  leadType: '',
  location: '',
  remarks: '',
  date: '',
};

export const COLUMNS = [
  { key: 'checkbox', label: '' },
  { key: 'action', label: 'Action' },
  { key: 'name', label: 'Name', sortable: true },
  { key: 'phone', label: 'Phone', sortable: true },
  { key: 'location', label: 'Location', sortable: true },
  { key: 'agentId', label: 'Assigned To', sortable: true },
  { key: 'purpose', label: 'Purpose', sortable: true },
  { key: 'type', label: 'Type', sortable: true },
  { key: 'status', label: 'Status', sortable: true },
  { key: 'source', label: 'Source', sortable: true },
  { key: 'createdAt', label: 'Created At', sortable: true },
  { key: 'updatedAt', label: 'Updated At', sortable: true },
  { key: 'nextFollowUpDate', label: 'Next Follow Up', sortable: true },
];
