import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Check, X } from 'lucide-react';
import { useWhatsappTemplatePage } from '../hooks';
import AddWhatsappTemplateDrawer from '../components/AddWhatsappTemplateDrawer';
import AdminDeleteModal from '../../../../shared/components/crud/AdminDeleteModal';
import PageHeader from '../../../../shared/components/layout/PageHeader';
import SettingsTabs from '../../../../shared/components/SettingsTabs';
import { SettingsTableLayout } from '../../../../shared/components/settings';
import { WHATSAPP_TEMPLATE_TABLE_COLUMNS } from '../constants/whatsappTemplateTableColumns';
const WhatsappTemplatePage = () => {
    const { whatsappTemplate, searchQuery, handleSearchChange, rowsPerPage, handleRowsPerPageChange, pageNumber, setPageNumber, totalCount, startIndex, totalPages, showDrawer, dropdownOpen, onToggleDropdown, editingItem, deletingItem, filteredData, drawerInitialValues, handleAddClick, handleCloseDrawer, handleEditClick, handleDeleteClick, handleConfirmDelete, handleCloseDeleteModal, handleSubmit, handleEditSubmit, } = useWhatsappTemplatePage();
    return (_jsxs("div", { className: "account-page", children: [_jsx(PageHeader, { title: "Account Settings", description: "Manage your login credentials, settings, and preferences" }), _jsx(SettingsTabs, {}), _jsxs("div", { className: "account-content", style: { width: '100%', maxWidth: '100%' }, children: [_jsx(SettingsTableLayout, { searchQuery: searchQuery, onSearchChange: handleSearchChange, onAdd: handleAddClick, addLabel: "Add Template", data: filteredData, columns: WHATSAPP_TEMPLATE_TABLE_COLUMNS, startIndex: startIndex, dropdownOpen: dropdownOpen, onToggleDropdown: onToggleDropdown, onEdit: handleEditClick, onDelete: handleDeleteClick, currentPage: pageNumber, totalPages: totalPages, rowsPerPage: rowsPerPage, totalItems: totalCount, onPageChange: setPageNumber, onRowsPerPageChange: handleRowsPerPageChange }), _jsx(AddWhatsappTemplateDrawer, { isOpen: showDrawer, onClose: handleCloseDrawer, validationSchema: editingItem ? whatsappTemplate.editValidationSchema : whatsappTemplate.validationSchema, initialValues: drawerInitialValues, onSubmit: editingItem ? handleEditSubmit : handleSubmit, isLoading: whatsappTemplate.isLoading, error: whatsappTemplate.error, isEditing: !!editingItem }), _jsx(AdminDeleteModal, { isOpen: !!deletingItem, itemName: deletingItem?.templateName || deletingItem?.name || '', onConfirm: handleConfirmDelete, onClose: handleCloseDeleteModal }), whatsappTemplate.showToast && (_jsxs("div", { className: `toast-notification toast-${whatsappTemplate.toastType}`, onClick: () => whatsappTemplate.setShowToast(false), children: [whatsappTemplate.toastType === 'success' ? _jsx(Check, { size: 18 }) : _jsx(X, { size: 18 }), _jsx("span", { children: whatsappTemplate.toastMessage })] }))] })] }));
};
export default WhatsappTemplatePage;
//# sourceMappingURL=WhatsappTemplatePage.js.map