import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Check, X } from 'lucide-react';
import { useDepartmentPage } from '../hooks';
import AddDepartmentDrawer from '../components/AddDepartmentDrawer';
import AdminDeleteModal from '../../../../shared/components/crud/AdminDeleteModal';
import PageHeader from '../../../../shared/components/layout/PageHeader';
import SettingsTabs from '../../../../shared/components/SettingsTabs';
import { SettingsTableLayout } from '../../../../shared/components/settings';
import { DEPARTMENT_TABLE_COLUMNS } from '../constants/departmentTableColumns';
const DepartmentPage = () => {
    const { department, searchQuery, handleSearchChange, rowsPerPage, handleRowsPerPageChange, pageNumber, setPageNumber, totalCount, startIndex, totalPages, showDrawer, dropdownOpen, onToggleDropdown, editingItem, deletingItem, filteredData, drawerInitialValues, handleAddClick, handleCloseDrawer, handleEditClick, handleDeleteClick, handleConfirmDelete, handleCloseDeleteModal, handleSubmit, handleEditSubmit, } = useDepartmentPage();
    return (_jsxs("div", { className: "account-page", children: [_jsx(PageHeader, { title: "Account Settings", description: "Manage your login credentials, settings, and preferences" }), _jsx(SettingsTabs, {}), _jsxs("div", { className: "account-content", style: { width: '100%', maxWidth: '100%' }, children: [_jsx(SettingsTableLayout, { searchQuery: searchQuery, onSearchChange: handleSearchChange, onAdd: handleAddClick, addLabel: "Add Department", data: filteredData, columns: DEPARTMENT_TABLE_COLUMNS, startIndex: startIndex, dropdownOpen: dropdownOpen, onToggleDropdown: onToggleDropdown, onEdit: handleEditClick, onDelete: handleDeleteClick, currentPage: pageNumber, totalPages: totalPages, rowsPerPage: rowsPerPage, totalItems: totalCount, onPageChange: setPageNumber, onRowsPerPageChange: handleRowsPerPageChange }), _jsx(AddDepartmentDrawer, { isOpen: showDrawer, onClose: handleCloseDrawer, validationSchema: editingItem ? department.editValidationSchema : department.validationSchema, initialValues: drawerInitialValues, onSubmit: editingItem ? handleEditSubmit : handleSubmit, isLoading: department.isLoading, error: department.error, isEditing: !!editingItem }), !!deletingItem && !department.dependencyError && (_jsx(AdminDeleteModal, { isOpen: !!deletingItem, itemName: deletingItem?.departmentName || deletingItem?.name || '', onConfirm: handleConfirmDelete, onClose: handleCloseDeleteModal })), department.dependencyError && (_jsx("div", { className: "modal-overlay", onClick: department.clearDependencyError, children: _jsxs("div", { className: "modal-content", onClick: (e) => e.stopPropagation(), style: { maxWidth: '450px' }, children: [_jsxs("div", { className: "modal-header", children: [_jsx("h5", { children: "Cannot Delete Department" }), _jsx("button", { className: "modal-close", onClick: department.clearDependencyError, children: _jsx(X, { size: 20 }) })] }), _jsx("div", { className: "modal-body", children: _jsx("p", { className: "delete-warning", children: "This department is currently assigned to one or more staff members. Please reassign or remove those staff members before deleting this department." }) }), _jsx("div", { className: "modal-footer", children: _jsx("button", { className: "btn btn-primary", onClick: department.clearDependencyError, children: "OK" }) })] }) })), department.showToast && (_jsxs("div", { className: `toast-notification toast-${department.toastType}`, onClick: () => department.setShowToast(false), children: [department.toastType === 'success' ? _jsx(Check, { size: 18 }) : _jsx(X, { size: 18 }), _jsx("span", { children: department.toastMessage })] }))] })] }));
};
export default DepartmentPage;
//# sourceMappingURL=DepartmentPage.js.map